### ISSUE TITLE
Not compliing 

### ISSUE THREAD

**Issue by Tidal-Tares** [NTStation/NTstation13#988]
loading tgstation.dme
loading interface\skin.dmf
code__HELPERS\text.dm:180:error: replacetext: invalid proc name: reserved word
code__HELPERS\text.dm:183:error: replacetextEx: invalid proc name: reserved word
code\game\objects\items\weapons\melee\energy.dm:185:error: throw: invalid proc name: reserved word
code\modules\mob\mob_grab.dm:45:error: throw: invalid proc name: reserved word
code\controllers\supply_shuttle.dm:683:error: replacetext: expected 3 to 5 arguments (found 1)
code\controllers\supply_shuttle.dm:493:error: replacetext: expected 3 to 5 arguments (found 1)
tgstation.dmb - 6 errors, 0 warnings (2/5/16 1:50 pm)

**Comment by Super3222** [comment]
Update byond to 510. @Tidal-Tares, if it's already updated to 510 it is probably because this code is outdated.

**Comment by Iamgoofball** [comment]
this codebase is nearing 2 years old

please stop using it

use tg code instead

# there's also a ton of security vulnerabilities in this code too

# use tgstation code instead https://github.com/tgstation/-tg-station

**Comment by Dawgas** [comment]
but /tg/station is pure shit because the diff from this point in /tg/station's history to now is mostly full of terribly executed gameplay changes, even though your point of better security and better optimized code stands

iirc, however, there's been changes to byond itself that make this code unable to function - if you found a decently old version of it it could still compile and run, but that isn't worth the effort.

ntstation didn't go far enough as far as being a fork, but it did get somewhat merged into /tg/station code

if you want ntstation 2.0 you'll have to fork /tg/'s code and work quite hard for little gain

**Comment by Iamgoofball** [comment]
Ignore @Dawgas he's a retard

**Comment by Iamgoofball** [comment]
Seriously if you do fork do it properly, or just commit your shit to tg because everything gets merged now
